### PR TITLE
fix: update control_plane_user_managed_keys.yaml

### PR DESCRIPTION
**Pull request by techcet**
Removing forward slash as Cloud KMS nor CA Service recognize the path

### CODE REVIEW

**Review by chuyang-deng — APPROVED** [review]

**Review by chuyang-deng — COMMENTED** [review]
Could you amend the commit message per: https://github.com/GoogleCloudPlatform/gke-policy-library/pull/216/checks?check_run_id=32309005162

**Comment by chuyang-deng** [comment]
@apeabody Hi Andrew, could you help to merge this PR when you get a chance?

**Comment by apeabody** [comment]
> @apeabody Hi Andrew, could you help to merge this PR when you get a chance?

Yup!

**Comment by techcet** [comment]
Thank you!

**Pull request merged**
